services:
  backend:
    image: jas0n4ndrw/todolist-backend:latest
    restart: always
    environment:
      PORT: 3168
      CONNECTION_URL: mongodb://e2425-wads-l4ccg7:doz8si5r@localhost:27018/?authSource=e2425-wads-l4ccg7
      REFRESH_TOKEN_SECRET: 1964a95447c951a7453ea22f2b36a0124da23b3d6b50c166bb441eea95930138
      EMAIL_USER: kelvinairplane@gmail.com
      EMAIL_PASSWORD: euyyujiopyukcraz
    ports:
      - "3042:3042"

  frontend:
    image: jas0n4ndrw/todolist-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3041:3041"