version: "3.8"

services:
  backend:
    image: DOCKER_USERNAME/.backend:latest
    restart: always
    environment:
      PORT: 5001
      CONNECTION_URL: mongodb+srv://jason:X86Iy0YSJpFybIMn@cluster0.grjrxcv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      REFRESH_TOKEN_SECRET: 1964a95447c951a7453ea22f2b36a0124da23b3d6b50c166bb441eea95930138
      EMAIL_USER: kelvinairplane@gmail.com
      EMAIL_PASSWORD: euyyujiopyukcraz
    ports:
      - "3042:3042"

  frontend:
    image: DOCKER_USERNAME/todolist/.frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3041:3041"